### ISSUE TITLE
效果如何

### ISSUE THREAD

**Issue by DavidJames2021** [hr2894235132/faster-livo#2]
非常感谢您的开源工作，想问一下有没有效果视频？

**Comment by hr2894235132** [comment]
> 非常感谢您的开源工作，想问一下有没有效果视频？

目前只进行了自己录制的数据集的测试，因为主要为了适配Mid-70，官方avia的数据集还没进行测试，但是avia的性能更好，相信效果也不会差。
视频的话目前只在livo-voxel_octree中上传了图片以及gift图，后面会慢慢完善。
