### ISSUE TITLE
关于时间同步咨询

### ISSUE THREAD

**Issue by Gatsby23** [hr2894235132/faster-livo#3]
感谢您在硬件方面做的突破。想咨询下有做Mid-70的时间同步吗？FAST-LIVO系列对硬件的时间同步要求高吗？

**Comment by hr2894235132** [comment]
> 感谢您在硬件方面做的突破。想咨询下有做Mid-70的时间同步吗？FAST-LIVO系列对硬件的时间同步要求高吗？

FAST-LIVO的工作是对传感器之间做了硬同步的，论文中说是通过stm32进行硬同步。我这里并没有利用外部硬件去做传感器间的时间同步。
